# Generated by Django 4.2.5 on 2023-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('profilepic', models.FileField(upload_to='car_app/static')),
                ('companyname', models.CharField(max_length=30)),
                ('companyemail', models.EmailField(max_length=254)),
                ('companyphone', models.IntegerField()),
                ('companyaddress', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
