# Generated by Django 4.2.5 on 2023-09-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_alter_upload_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_product',
            name='category',
            field=models.CharField(choices=[('SEDAN', 'sedan'), ('SUV', 'suv'), ('HATCHBACK', 'hatchback')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
