# Generated by Django 4.2.5 on 2023-09-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_upload_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('pro_img', models.FileField(upload_to='')),
                ('pro_name', models.CharField(max_length=30)),
                ('pro_des', models.CharField(max_length=30)),
                ('pro_km', models.IntegerField()),
                ('pro_price', models.IntegerField()),
                ('pro_fuel', models.CharField(max_length=30)),
                ('pro_owner', models.CharField(max_length=30)),
                ('pro_category', models.CharField(max_length=30)),
            ],
        ),
    ]
