# Generated by Django 4.2.5 on 2023-09-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('profilepic', models.FileField(upload_to='car_app/static')),
                ('address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
