# Generated by Django 4.2.5 on 2023-09-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0006_reg_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_product',
            name='fuel',
            field=models.CharField(choices=[('PETROL', 'petrol'), ('DIESEL', 'diesel'), ('EV', 'ev')], max_length=30),
        ),
    ]
