# Generated by Django 4.2.5 on 2023-09-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0007_alter_upload_product_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='pro_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
