# Generated by Django 4.2.5 on 2023-09-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0010_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('fullname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('postal', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
