# Generated by Django 4.2.5 on 2023-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0011_checkout_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='details_full',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('product_list', models.CharField(max_length=300)),
                ('total_price', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('estimated_date', models.DateField()),
            ],
        ),
    ]
