# Generated by Django 4.2.5 on 2023-10-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0012_details_full'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkout_model',
            new_name='address',
        ),
    ]
