# Generated by Django 4.2.5 on 2023-10-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0013_rename_checkout_model_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='address',
            new_name='delivery_address',
        ),
    ]
